import { useState, useEffect } from 'react';
import { Pin, X, Bot, Bookmark, Loader2, Info } from 'lucide-react';
import api from '../../api';
import { useApp } from '../../context/AppContext';
import { Button } from '../../components/Button';

export default function Insights() {
  const { showToast } = useApp();
  const [insight, setInsight] = useState(null);
  const [tips, setTips] = useState([]);
  const [loadingInsights, setLoadingInsights] = useState(true);
  const [loadingTips, setLoadingTips] = useState(true);

  useEffect(() => {
    const fetchInsights = async () => {
      try {
        const res = await api.get('/api/ai/monthly-insights');
        if (res.data.success) setInsight(res.data.data);
      } catch (err) {
        console.error('Failed to fetch insights', err);
      }
      setLoadingInsights(false);
    };

    const fetchTips = async () => {
      try {
        const res = await api.get('/api/ai/saving-tips');
        if (res.data.success) setTips(res.data.data);
      } catch (err) {
        console.error('Failed to fetch tips', err);
      }
      setLoadingTips(false);
    };

    fetchInsights();
    fetchTips();
  }, []);

  const handleToggleTipPin = async (tipId) => {

    setTips(tips.map(t => t._id === tipId ? { ...t, isPinned: !t.isPinned } : t));
    try {
      await api.post(`/api/ai/saving-tips/${tipId}/pin`);
    } catch (err) {
      showToast('Failed to pin tip', 'error');

      setTips(tips.map(t => t._id === tipId ? { ...t, isPinned: !t.isPinned } : t));
    }
  };

  const handleBookmarkInsight = async (insightId) => {
    try {
      const res = await api.post('/api/bookmarks', { refType: 'insight', refId: insightId, note: 'Bookmarked from Insights page' });
      if (res.data.success) {
        showToast('Insight saved to bookmarks!', 'success');
      }
    } catch (err) {
      if (err.response?.status === 409) {
         showToast('Insight is already bookmarked', 'info');
      } else {
         showToast('Failed to bookmark insight', 'error');
      }
    }
  };

  const handleDismissTip = async (tipId) => {

    const previous = [...tips];
    setTips(tips.filter(t => t._id !== tipId));
    try {
      await api.post(`/api/ai/saving-tips/${tipId}/dismiss`);
    } catch (err) {
      showToast('Failed to dismiss tip', 'error');

      setTips(previous);
    }
  };

  const activeTips = tips.filter(t => !t.dismissed);

  return (
    <div className="animate-fade-in space-y-8 max-w-4xl">
      <div>
        <h1 className="text-2xl font-extrabold text-cc-forest flex items-center gap-2">
          <Bot className="w-7 h-7 text-cc-lime" /> AI Insights &amp; Saving Tips
        </h1>
        <div className="flex items-center gap-1.5 mt-2 bg-blue-50 text-blue-800 border border-blue-200 px-3 py-1.5 rounded-xl w-fit text-xs font-medium">
          <Info className="w-3.5 h-3.5" />
          AI insights are generated by an LLM and may not be 100% accurate.
        </div>
      </div>

      <section className="space-y-4">
        <h2 className="font-bold text-cc-forest">Monthly Insight</h2>
        {loadingInsights ? (
           <div className="flex items-center justify-center py-10 bg-white border border-gray-100 rounded-2xl shadow-sm">
              <Loader2 className="w-6 h-6 animate-spin text-cc-lime" />
           </div>
        ) : insight ? (
          <div className="bg-white rounded-2xl border border-gray-100 p-5 shadow-sm">
            <div className="flex items-start justify-between gap-3 mb-3">
              <div>
                <span className="text-xs font-bold uppercase text-cc-lime tracking-wide">
                  Current Month Summary
                </span>
                <p className="text-[11px] text-cc-muted mt-0.5">
                  Source: {insight.source === 'gemini' ? 'AI Generated (Gemini)' : 'Template Fallback'}
                </p>
              </div>
              <button
                type="button"
                className="p-2 rounded-lg text-cc-muted hover:bg-gray-50 hover:text-cc-lime transition"
                title="Save to Bookmarks"
                onClick={() => handleBookmarkInsight(insight._id)}
              >
                <Bookmark className="w-4 h-4" />
              </button>
            </div>
            <p className="text-sm text-cc-ink leading-relaxed mb-3">{insight.text}</p>
          </div>
        ) : (
          <div className="bg-white rounded-2xl border border-dashed border-gray-200 p-8 text-center text-sm text-cc-muted">
            Not enough data to generate an insight this month.
          </div>
        )}
      </section>

      <section className="space-y-4">
        <h2 className="font-bold text-cc-forest">Personalized Saving Tips</h2>
        <p className="text-xs text-cc-muted -mt-2">Actionable tips based on your spending history</p>

        {loadingTips ? (
           <div className="flex items-center justify-center py-10 bg-white border border-gray-100 rounded-2xl shadow-sm">
              <Loader2 className="w-6 h-6 animate-spin text-cc-lime" />
           </div>
        ) : activeTips.length > 0 ? (
          activeTips.map((tip) => (
            <div key={tip._id} className="bg-white rounded-2xl border border-gray-100 p-4 shadow-sm flex gap-3 items-start">
              <div className="flex-1">
                <span className="text-[10px] font-bold uppercase px-2 py-0.5 rounded-full bg-cc-mint text-cc-lime-dark">
                  Actionable Idea
                </span>
                <p className="text-sm text-cc-ink mt-2">{tip.text}</p>
              </div>
              <div className="flex gap-1 shrink-0">
                <button
                  type="button"
                  onClick={() => handleToggleTipPin(tip._id)}
                  className={`p-2 rounded-lg ${tip.isPinned ? 'bg-cc-mint text-cc-lime' : 'text-cc-muted hover:bg-gray-50'}`}
                  title={tip.isPinned ? 'Unpin' : 'Pin tip'}
                >
                  <Pin className={`w-4 h-4 ${tip.isPinned ? 'fill-current' : ''}`} />
                </button>
                <button
                  type="button"
                  onClick={() => handleDismissTip(tip._id)}
                  className="p-2 rounded-lg text-cc-muted hover:bg-red-50 hover:text-red-500"
                  title="Dismiss"
                >
                  <X className="w-4 h-4" />
                </button>
              </div>
            </div>
          ))
        ) : (
          <p className="text-sm text-cc-muted text-center py-8 bg-white rounded-2xl border border-dashed">
            All tips dismissed. New ones appear as you log more transactions.
          </p>
        )}
      </section>
    </div>
  );
}
