import PDFDocument from 'pdfkit';
import { User } from '../models/User.js';
import { getDashboardSummary } from './dashboardService.js';
import { getCategoryBreakdown } from './reportService.js';

/**
 * Generate monthly financial report PDF stream.
 */
export const generateReportPdfStream = async (userId, res) => {
  const user = await User.findById(userId);
  const summary = await getDashboardSummary(userId);
  const breakdown = await getCategoryBreakdown(userId, { type: 'expense' });

  const doc = new PDFDocument({ margin: 50 });

  // Set HTTP Headers for PDF download
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename=CampusCoin_Report_${summary.month}.pdf`);

  doc.pipe(res);

  // Header Banner
  doc.rect(0, 0, doc.page.width, 80).fill('#4F46E5');
  doc.fillColor('#FFFFFF').fontSize(22).text('CAMPUS COIN - FINANCIAL REPORT', 50, 25);
  doc.fontSize(12).text(`Student Spending & Budget Overview (${summary.month})`, 50, 52);

  doc.moveDown(3);
  doc.fillColor('#111827');

  // Student Profile Card
  doc.fontSize(14).text(`Student Name: ${user.name}`, { underline: false });
  doc.fontSize(11).text(`Email: ${user.email}`);
  doc.text(`Academic Year: ${user.academicYear}`);
  doc.text(`Report Period: ${summary.month}`);

  doc.moveDown();
  doc.strokeColor('#E5E7EB').lineWidth(1).moveTo(50, doc.y).lineTo(550, doc.y).stroke();
  doc.moveDown();

  // Monthly Overview Totals Table
  doc.fontSize(14).text('Monthly Overview');
  doc.moveDown(0.5);

  doc.fontSize(11);
  doc.text(`Total Income: $${summary.totals.income.toFixed(2)}`);
  doc.text(`Total Expense: $${summary.totals.expense.toFixed(2)}`);
  doc.text(`Net Balance: $${summary.totals.balance.toFixed(2)}`);

  doc.moveDown();
  doc.strokeColor('#E5E7EB').lineWidth(1).moveTo(50, doc.y).lineTo(550, doc.y).stroke();
  doc.moveDown();

  // Expense Category Breakdown Table
  doc.fontSize(14).text('Expense Breakdown by Category');
  doc.moveDown(0.5);

  if (breakdown.categories.length === 0) {
    doc.fontSize(10).fillColor('#6B7280').text('No expense transactions recorded for this period.');
  } else {
    // Table Header
    doc.fontSize(10).fillColor('#374151');
    doc.text('Category', 50, doc.y, { width: 200, continued: true });
    doc.text('Total Spent', { width: 150, continued: true });
    doc.text('Percentage', { width: 100 });
    doc.moveDown(0.5);

    breakdown.categories.forEach((cat) => {
      doc.fontSize(10).fillColor('#1F2937');
      doc.text(cat.name, 50, doc.y, { width: 200, continued: true });
      doc.text(`$${cat.total.toFixed(2)}`, { width: 150, continued: true });
      doc.text(`${cat.percentage}%`, { width: 100 });
      doc.moveDown(0.3);
    });
  }

  // Footer / Disclaimer
  doc.moveDown(3);
  doc.fontSize(9).fillColor('#9CA3AF').text('Generated by Campus Coin - Smart Spending Student Style.', 50, doc.page.height - 50, {
    align: 'center'
  });

  doc.end();
};
